/// <reference path="../node_modules/angular2/bundles/typings/angular2/angular2.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/http.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/router.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/testing.d.ts" />
/// <reference path="../node_modules/angular2/typings/es6-shim/es6-shim.d.ts"/>
/// <reference path="../node_modules/angular2/typings/zone/zone.d.ts"/>
/// <reference path="../node_modules/angular2/typings/hammerjs/hammerjs.d.ts"/>
/// <reference path="../node_modules/angular2/typings/jasmine/jasmine.d.ts"/>
/// <reference path="../node_modules/definition-header/dist/index.d.ts" />
/// <reference path="../node_modules/reflect-metadata/reflect-metadata.d.ts" />
/// <reference path="../node_modules/immutable/dist/immutable.d.ts" />
/// <reference path="jquery/jquery.d.ts" />
/// <reference path="select2/select2.d.ts" />
/// <reference path="lodash/lodash.d.ts" />
